### ISSUE TITLE
Where do you put you bible modules

### ISSUE THREAD

**Issue by OrionRandD** [tobias-klein/ezra-project#19]
Where ezra-project saves its bible modules?
I am asking it because I have got diatheke, xiphos, and bibletime here in my debian.
The modules (bibles, commentaries, books, etc.) are saved in /usr/share/sword for system-wide users and they also are pulled from crosswire project. So, If I had to download all the modules again, just for ezra-project I will have a waste of space in my HD, since I have got more than 1.5GB of modules aready installed.
Thx.

**Comment by tobias-klein** [comment]
Hi! Bible modules wouldn't be redownloaded if they are already available in the local Sword folders. However, Ezra Project imports the content of Bible modules into its own database and that of course takes additional space.
