### ISSUE TITLE
libsword11v5 not available for download on Ubuntu 19.04

### ISSUE THREAD

**Issue by entodoays** [tobias-klein/ezra-project#3]
It seems that libsword-1.8.1 has replaced libsword11v5. Would it be possible to update Ezra to make it work with libsword 1.8.1?

**Comment by tobias-klein** [comment]
I just added custom Debian packages for Ubuntu 18.04 and Ubuntu 19.04, you can find them on the latest release page. Can you try the Ubuntu 19.04 Debian package? That depends on libsword-1.8.1.

**Comment by entodoays** [comment]
Installed it and it seems to be working fine. You should update the Linux installation instructions.

**Comment by tobias-klein** [comment]
Cool, closing this issue then! Consider providing additional feedback after using Ezra Project for a bit!
