### ISSUE TITLE
Sword path

### ISSUE THREAD

**Issue by DavidHaslam** [tobias-klein/ezra-project#5]
Please tweak Ezra to use the same Sword path in Linux and Windows as do other front-ends such as Xiphos.

Then all modules already installed using Xiphos, or created locally using Sword tools will be immediately available to Ezra.

Refer to email thread in sword-devel mailing list.

David

**Comment by tobias-klein** [comment]
Fixed. Fix will be available in upcoming version 0.8.1.

**Comment by alerque** [comment]
I haven't inspected the actual behavior yet, but the release notes for 0.8.1 make it sound like you are copying modules found in the normal Sword paths into another location. Is that what you did? If so why not just use them in place?

**Comment by tobias-klein** [comment]
It's part of the concept in Ezra Project that I'm putting the content of 
the Sword modules into a local sqlite database.
I've been thinking about changing that, but that's how it is right now. 
I've been using Ezra Project already before I integrated it with Sword 
and haven't changed the interface to the text yet. So at the moment the 
text is accessed through a database.

Am 21/06/2019 um 10:08 schrieb Caleb Maclennan:

**Comment by alerque** [comment]
Okay so the sync is to a different format, not just shuffling same-format content around for the sake of it being in a different place. I'm good with that. Long term if using Sword content is the way to go skipping the intermediate formate altogether might be nice, but I don't have an issue with taking things one step at a time. Finding the modules I already have downloaded for use in other apps is a great step forward!

Thanks for the clarification.

**Comment by tobias-klein** [comment]
The backend (node-sword-interface) should now behave like any other 
Sword based tool. The method "getAllLocalModules" should return 
everything installed by any Sword frontend. This is the base for my 
module sync function in Ezra Project.

See 
https://github.com/tobias-klein/node-sword-interface/blob/master/API.md#NodeSwordInterface+getAllLocalModules
