### ISSUE TITLE
Highlight module search results

### ISSUE THREAD

**Issue by tobias-klein** [tobias-klein/ezra-project#52]
Module search results shall be highlighted for all three search options:
* Multi-word search
* Exact phrase search
* Strong's search

**Comment by alerque** [comment]
Note, there is an active thread on the sword-devel list (or was it the Xiphos one) about search result highlighting. This is functionality that it would be useful to move upstream to SWORD rather than having to rehash in every client.

**Comment by tobias-klein** [comment]
Yes! I actually started the thread on the sword mailing list. Currently there's no generic solution available in SWORD. When implementing this for Ezra Project, the change would be needed in node-sword-interface. Once starting to work on this I'll check whether I can actually supply a patch for SWORD.

**Comment by alerque** [comment]
> Yes! I actually started the thread on the sword mailing list.

Savvy. Shows how long my attention bandwidth is right now, sorry.

**Comment by tobias-klein** [comment]
I found that I can re-use the existing JS implementation of search result highlighting that I already used for the "in tab search" functionality (CTRL + f). So for now I'm using that.
