### ISSUE TITLE
Oversized Strong's box / text not readable completely

### ISSUE THREAD

**Issue by LAfricain** [tobias-klein/ezra-project#9]
See the capture, the definition of the strong number can't be read completly because the windows is cut:
![windows_cuts](https://user-images.githubusercontent.com/19690477/67990835-7806d980-fc0d-11e9-856f-8f74949f1fd1.png)

You the sentence ending with pair of balance, we can't read the end of the sentence.

**Comment by tobias-klein** [comment]
For some reason the Strong's box is not properly "resizing". Usually this should happen at start up and also every time the size of the overall window changes. What happens if you resize the overall window?
